version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
      - npm i
  build:
    commands:
      - npm run build
      - aws s3 rm s3://coding229148.react-app --recursive
      - aws s3 sync "public/" "s3://coding229148.react-app" --delete