name: build-and-upload-to-s3
run-name: Build and upload to S3
on: [push]
jobs:
  push-to-code-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - uses: actions/checkout@v3
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npm run build
      - run: aws s3 sync "public/" "s3://coding229148.react-app" --delete