name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  push-to-code-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAUE7MXOVG734NVV7A
          aws-secret-access-key: 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
          aws-region: ap-southeast-1
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: aws s3 sync "public/" "s3://coding229148.react-app" --delete